Work-about sections
daudi13/portfolio pull request #2
Opened 2022-01-07 15:36 UTC by daudi13

#in this project I:

-Added the work section to .html
-Added about section to .html
-Added each file on a unique commit
-Fixed linter errors
-used flexbox and grid in placing elements
-updated .css file

2022-01-07 16:07 UTC, ReshyResh requested changes
# Hi @daudi13  , 

You did a really good good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

To highlight:
  - ✔Descriptive commit messages.
  - ✔Design matches template requirements.
  - ✔Used `flex` correctly to display the content of the cards.


## Required Changes ♻️
_Please check the comments under the review._

----

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 16:07 UTC, ReshyResh commented on index.html
> +				<div class="work-section__card--info">
- [x] You did a good job using `flex` to display the elements inside the work cards, however, as per requirement, the `<section>` tag including all the cards should use a `display:grid` property.

2022-01-07 16:07 UTC, ReshyResh commented on index.html
> +						<div class="tech__type">javaScript</div>
- [x] As per requirement, list items should be inside a `<ul>` tag, with each element being a list item `<li>`. Please make sure to apply the changes to all the cards.

2022-01-07 16:07 UTC, ReshyResh commented on index.html
> +			<div class="language-section__box-sec">
- [x] The section under the `Get my resume` button should be a list, with the elements containing items being another list.
The final structure should be as follows:
  - ul
     - li (Language)
         - ul
             - li (Javascript)
             - li (HTML)
             - li (CSS)
         - /ul
      - /li
      -  ...

2022-01-07 16:07 UTC, ReshyResh commented on style.css
> +}
- [x] Please make sure to follow the desing guidelines and align the pictures in the middle, currently they're leaning on the left side.
- [x] Also please make sure to add some margin between each individual card, to space it from the one right under it.

![](https://i.imgur.com/vftmGM3.png)

2022-01-08 04:08 UTC, mateo951 commented on index.html
> +				<div class="work-section__card--info">
Addressed ✔

2022-01-08 04:08 UTC, mateo951 commented on style.css
> +}
Addressed ✔

2022-01-08 04:08 UTC, mateo951 commented on index.html
> +			<div class="language-section__box-sec">
Addressed ✔

2022-01-08 04:08 UTC, mateo951 commented on index.html
> +						<div class="tech__type">javaScript</div>
Addressed ✔

2022-01-08 04:10 UTC, mateo951 approved these changes
Hi @daudi13, 

Awesome job at making the required changes asked by the previous reviewer 🧐✔Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 15:33 UTC, merged